export default {
	AUTH_REDIRECTURL: AUTH_REDIRECTURL,
	AUTH0_CLIENT_ID: AUTH0_CLIENT_ID,
	AUTH0_DOMAIN: AUTH0_DOMAIN,
	BASE_API: BASE_API,
	AUTH0_SIGNUP_URL: AUTH0_SIGNUP_URL,
	AUTH0_DB_CONNECTION: AUTH0_DB_CONNECTION
};
